name: Lint
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install screens
        run: yarn
      - name: Run ESLint
        run: yarn lint
